# -*- coding: utf-8 -*-
"""protocol_loader.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1LNkImzcJBU-Ov6E3JfypY9X-6_DiAZ6-
"""

import os
from typing import List, Dict, Any

def load_protocol_yaml(file_path: str) -> List[Dict[str, Any]]:
    """
    Загружает протокол из YAML-файла и возвращает список правил.

    Ожидаемый формат YAML:
    rules:
      - id: "R1"
        type: "inclusion"
        field: "lvef"
        operator: "<="
        value: 40
        description: "LVEF ≤ 40%"

    Args:
        file_path: путь к YAML-файлу (например, "protocols/dapa_hf.yaml")

    Returns:
        Список правил в виде словарей.
    """
    if not os.path.exists(file_path):
        raise FileNotFoundError(f"Protocol file not found: {file_path}")

    try:
        import yaml
    except ImportError:
        raise ImportError(
            "PyYAML is required to load protocol files. "
            "Install it with: pip install PyYAML"
        )

    with open(file_path, "r", encoding="utf-8") as f:
        data = yaml.safe_load(f)

    if not isinstance(data, dict):
        raise ValueError("Invalid YAML: root must be a dictionary")

    if "rules" not in data:
        raise ValueError("Invalid protocol: missing 'rules' key")

    rules = data["rules"]
    if not isinstance(rules, list):
        raise ValueError("'rules' must be a list")

    # Базовая валидация каждого правила
    for i, rule in enumerate(rules):
        if not isinstance(rule, dict):
            raise ValueError(f"Rule {i} is not a dictionary")
        required_keys = {"id", "type", "field", "operator", "value"}
        if not required_keys.issubset(rule.keys()):
            missing = required_keys - rule.keys()
            raise ValueError(f"Rule {rule.get('id', i)} missing keys: {missing}")

    return rules